# Generated by Django 3.2.5 on 2022-11-18 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_to_locations', to='masterapp.customers'),
        ),
    ]
