# Generated by Django 3.2.8 on 2022-09-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, unique=True)),
                ('gln_number', models.CharField(max_length=22)),
                ('address', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(choices=[('system_pc', 'system_pc'), ('ipc', 'ipc')], max_length=20)),
                ('system_name', models.CharField(max_length=40)),
                ('line', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('manufacturinglocation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufactorlocation_to_productionline', to='productionlineapp.manufacturinglocations')),
            ],
            options={
                'db_table': 'RegisteredSystem',
            },
        ),
        migrations.AddConstraint(
            model_name='registeredsystem',
            constraint=models.UniqueConstraint(fields=('manufacturinglocation_id', 'name'), name='oneproline'),
        ),
    ]
