# Generated by Django 3.2.16 on 2022-10-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionlineapp', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturinglocations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
