# Generated by Django 3.2.16 on 2022-10-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_order_number', models.CharField(max_length=100, unique=True)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('manufacture_loc_name', models.CharField(max_length=50)),
                ('line_name', models.CharField(max_length=100)),
                ('system_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
