# Generated by Django 3.2.16 on 2022-10-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0002_alter_productionreport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
