# Generated by Django 3.2.16 on 2022-10-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0003_auto_20221027_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='process_order_number',
            field=models.CharField(max_length=100),
        ),
    ]
