# Generated by Django 3.2.16 on 2022-10-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0004_alter_productionreport_process_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='batch_number',
            field=models.CharField(default='batch number', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='created_by',
            field=models.CharField(default='created by', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='line_name',
            field=models.CharField(default='line name', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='manufacture_loc_name',
            field=models.CharField(default='manufacture location name', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='process_order_number',
            field=models.CharField(default='process order number', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='product_name',
            field=models.CharField(default='product name', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='system_name',
            field=models.CharField(default='system name', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
