# Generated by Django 3.2.16 on 2022-10-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGetTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_event', models.CharField(blank=True, max_length=100, null=True)),
                ('app_message', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('datebirth', models.DateField()),
                ('age', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=100)),
                ('date_join', models.DateTimeField()),
                ('educational_qualification', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('dummy1', models.CharField(blank=True, max_length=100, null=True)),
                ('dummy2', models.CharField(blank=True, max_length=100, null=True)),
                ('dummy3', models.CharField(blank=True, max_length=100, null=True)),
                ('dummy4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('date_birth', models.DateField(null=True)),
                ('age', models.CharField(default='age', max_length=100)),
                ('place', models.CharField(default='place', max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField(default='address')),
                ('mobile', models.CharField(default='phone', max_length=100)),
                ('userRole', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
