# Generated by Django 3.2.16 on 2022-10-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appgettracker_reg_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='conpass',
            field=models.CharField(default='confirm password', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='date_join',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='dummy1',
            field=models.CharField(default='dummy1', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='dummy2',
            field=models.CharField(default='dummy2', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='dummy3',
            field=models.CharField(default='dummy3', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='dummy4',
            field=models.CharField(default='dummy4', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='eduqu',
            field=models.CharField(default='qualification', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='uname',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
