# Generated by Django 3.2.16 on 2022-10-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_uname_register_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='uname',
        ),
    ]
