# Generated by Django 3.2.16 on 2022-10-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221014_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='uname',
            new_name='username',
        ),
    ]
