# Generated by Django 3.2.16 on 2022-10-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221014_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
